version: '3.0'
services:
  death-code:
    container_name: death-code
    build:
      context: .
    restart: unless-stopped
    ports:
      - 33284:80
    depends_on: 
      - rust-captcha
    environment:
      - END_URL=${END_URL} # If attempt is successful, redirect to this URL
      - DOMAIN=${DOMAIN} # The domain this will be hosted on
      - COEFFICIENTS_AND_MOD=${COEFFICIENTS_AND_MOD} # For example, [3, 5, 23] represents the function f(x)=3x+5 mod 23
      - ALIVE_PATH=${ALIVE_PATH} # Path to deny allowing attempts immediately and start the countdown (optional)
      - DAYS_TO_ALLOW=${DAYS_TO_ALLOW} # How many days to GET alive endpoint until death code starts allowing attemps (optional)
      - DEAD_PATH=${DEAD_PATH} # Path to start allowing attemps immediately (optional)
  rust-captcha:
    container_name: rust-captcha
    build:
      context: ../rust-captcha/docker
    restart: unless-stopped
    